library(igraph)
data <- read.csv("friendship_data.csv")
graph <- graph_from_data_frame(data, directed = FALSE)
plot(graph, vertex.size=5, vertex.label.cex=0.8, main="Friendship Network")
degree_cent <- degree(graph)
print(degree_cent)
betweenness_cent <- betweenness(graph)
print(betweenness_cent)
closeness_cent <- closeness(graph)
print(closeness_cent)
cliques_list <- cliques(graph)
print(cliques_list)
max_cliques <- largest_cliques(graph)
print(max_cliques)
communities <- cluster_louvain(graph)
plot(communities, graph, main="Community Detection in Network")